#端口 数据源 thymeleaf、mybatis、表单转换
server:
  port: 9091

spring:
  datasource:
    username: root
    password: everything@123456Qwqe
    url: jdbc:mysql://120.79.149.40:3306/laydb?serverTimezone=GMT%2B8

  thymeleaf:
    cache: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true
      throw-exception-if-no-handler-found: true  #出现异常直接抛出
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.example.*.pojo #别名
  configuration:
    map-underscore-to-camel-case: true #驼峰转换
logging:
  level:
    com.example: debug
